1.Check and prepare data to clean and handling missing values and ensuring consistency.
2.Summaries the data with statistical analysis: Use descriptive statistics with aggregation function (i.e sum, count, average, min, max) for searching meaningful information such as: top product sales, total amount, average amount, etc
3.Use Statistical methods to identify significant correlation/comparative/distribution/trending between variables from the data
4.Visualize the data with charts and graphs to see patterns and relationships (min.3 graph)
5.Use related python library to handle all of tasks 
6.Upload your source code with python extension file such as .py or .ipynb and file  .rawgraphs (if you visualized the data using rawgraphs)
7.Tomorrow some of you will present the result of your assignment

In [2]:

import pandas as pd

In [5]:
data = pd.read_csv('./orderdataset.csv' ,sep=';')
data.info()
# data = data.drop('order_id' ,axis = 1)
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               49999 non-null  object
 1   quantity               49999 non-null  int64
 2   product_id             49999 non-null  object
 3   price                  49999 non-null  int64
 4   seller_id              49999 non-null  object
 5   freight_value          49999 non-null  int64
 6   customer_id            49999 non-null  object
 7   order_status           49999 non-null  object
 8   purchase_date          49999 non-null  object
 9   payment_type           49999 non-null  object
 10  product_category_name  49999 non-null  object
 11  product_weight_gram    49980 non-null  float64
dtypes: float64(1), int64(3), object(8)
memory usage: 4.6+ MB

,order_id,quantity,product_id,price,seller_id,freight_value,customer_id,order_status,purchase_date,payment_type,product_category_name,product_weight_gram
0,2e7a8482f6fb09756ca50c10d7bfc047,2,f293394c72c9b5fafd7023301fc21fc2,1489000,1554a68530182680ad5c8b042c3ab563,28000,08c5351a6aca1c1589a38f244edeee9d,shipped,05/09/2016,virtual account,fashion,1800.0
1,2e7a8482f6fb09756ca50c10d7bfc047,1,c1488892604e4ba5cff5b4eb4d595400,1756000,1554a68530182680ad5c8b042c3ab563,45000,08c5351a6aca1c1589a38f244edeee9d,shipped,05/09/2016,virtual account,automotive,1400.0
2,e5fa5a7210941f7d56d0208e4e071d35,1,f3c2d01a84c947b078e32bbef0718962,1707000,a425f92c199eb576938df686728acd20,174000,683c54fc24d40ee9f8a6fc179fd9856c,canceled,05/09/2016,e-wallet,toys,700.0
3,3b697a20d9e427646d92567910af6d57,1,3ae08df6bcbfe23586dd431c40bddbb7,3071000,522620dcb18a6b31cd7bdf73665113a9,154000,355077684019f7f60a031656bd7262b8,delivered,03/10/2016,e-wallet,utilities,300.0
4,71303d7e93b399f5bcd537d124c0bcfa,1,d2998d7ced12f83f9b832f33cf6507b6,3833000,25e6ffe976bd75618accfe16cefcbd0d,147000,b106b360fe2ef8849fbbd056f777b4d5,canceled,03/10/2016,e-wallet,fashion,500.0

In [10]:
data['seller_id'].nunique()
# data.drop('seller_id_num' , axis = 1 , inplace = True)

# Giving unique id to seller_id , order_id , product_id , customer_id
data['order_id'], unique = pd.factorize(data['order_id'])
data['product_id'], unique = pd.factorize(data['product_id'])
data['seller_id'], unique = pd.factorize(data['seller_id'])
data['customer_id'], unique = pd.factorize(data['customer_id'])

print(data['order_id'].nunique())
print(data['product_id'].nunique())
print(data['seller_id'].nunique())
print(data['customer_id'].nunique())

42694
16866
1777
42694

In [14]:
print(data.duplicated().unique())
print(data.isnull().sum())
data.head()

[False]
order_id                  0
quantity                  0
product_id                0
price                     0
seller_id                 0
freight_value             0
customer_id               0
order_status              0
purchase_date             0
payment_type              0
product_category_name     0
product_weight_gram      19
dtype: int64

,order_id,quantity,product_id,price,seller_id,freight_value,customer_id,order_status,purchase_date,payment_type,product_category_name,product_weight_gram
0,0,2,0,1489000,0,28000,0,shipped,05/09/2016,virtual account,fashion,1800.0
1,0,1,1,1756000,0,45000,0,shipped,05/09/2016,virtual account,automotive,1400.0
2,1,1,2,1707000,1,174000,1,canceled,05/09/2016,e-wallet,toys,700.0
3,2,1,3,3071000,2,154000,2,delivered,03/10/2016,e-wallet,utilities,300.0
4,3,1,4,3833000,3,147000,3,canceled,03/10/2016,e-wallet,fashion,500.0

2.Summaries the data with statistical analysis: Use descriptive statistics with aggregation function 
(i.e sum, count, average, min, max) for searching meaningful information such as: top product sales, total amount, average amount, etc

In [30]:
#Order status, payment types, and product categories
print(f"Order Details : {data['order_status'].value_counts()}")
print(f"Different type of payment : {data['payment_type'].value_counts()}")
print(f"Different type of category : {data['product_category_name'].value_counts()}")


print(f"Total Amount of sales: {data['price'].sum()}")
print(f"Average sales / order: {data['price'].mean()}")

#sales per category
totalsalesCategory = data.groupby('product_category_name')['price'].sum()
print(f"Totalsales / category : {totalsalesCategory}")

#average weight of products
print(f"Average weight of product in gram: {data['product_weight_gram'].mean()}")

#maximum and minimum sales per category
print(f"Category with maximum sales is {totalsalesCategory.idxmax()} with sales of {totalsalesCategory.max()}")
print(f"Category with minimum sales is {totalsalesCategory.idxmin()} with sales of {totalsalesCategory.min()}")

#average shipping cost
print(f"Average shipping cost of an order: {data['freight_value'].mean()}")

# Top product sales by quantity with category information
top_products = data.groupby(['product_id', 'product_category_name']).size().sort_values(ascending=False).head(10)
print(f"Top 10 products by quantity sold with category information:\n{top_products}")

# Total sales amount per seller
total_sales_seller = data.groupby('seller_id')['price'].sum().sort_values(ascending=False).head(10)
print(f"Top 10 sellers by total sales amount:\n{total_sales_seller}")

# Total quantity sold per category
total_quantity_category = data.groupby('product_category_name')['order_id'].count()
print(f"Total quantity sold per category:\n{total_quantity_category}")

# Average freight value per seller
average_freight_seller = data.groupby('seller_id')['freight_value'].mean().sort_values(ascending=False).head(10)
print(f"Average freight value per seller:\n{average_freight_seller}")

# Total sales amount per customer
total_sales_customer = data.groupby('customer_id')['price'].sum().sort_values(ascending=False).head(10)
print(f"Top 10 customers by total sales amount:\n{total_sales_customer}")

# Customer lifetime value (total sales per customer)
customer_lifetime_value = data.groupby('customer_id')['price'].sum().sort_values(ascending=False)
print(f"Customer lifetime value (total sales per customer):\n{customer_lifetime_value}")

# Median sales per order
median_sales_order = data['price'].median()
print(f"Median sales per order: {median_sales_order}")

# Sales distribution by payment type
sales_distribution_payment = data.groupby('payment_type')['price'].sum()
print(f"Sales distribution by payment type:\n{sales_distribution_payment}")

#find popular payment method
popular_payment_type = data['payment_type'].value_counts().idxmax()
print(f"Most popular payment type: {popular_payment_type}")

#find what category is most canceled
#filter it
canceled_orders = data[data['order_status'] == 'canceled']

#coutn cancel by each category
canceled_orders_per_category = canceled_orders['product_category_name'].value_counts()

#find the most canceled one
most_canceled_category = canceled_orders_per_category.idxmax()
most_canceled_count = canceled_orders_per_category.max()

print(f"Product category with the most canceled orders: {most_canceled_category}")
print(f"Number of canceled orders in this category: {most_canceled_count}")

#do the same for what category sucessfully delivered
#couny delivered by each category
delivered_orders = data[data['order_status'] == 'delivered']
delivered_orders_per_category = delivered_orders['product_category_name'].value_counts()
most_delivered_category = delivered_orders_per_category.idxmax()
most_delivered_count = delivered_orders_per_category.max()

print(f"Product category with the most successful orders: {most_delivered_category}")
print(f"Number of delivered orders in this category: {most_delivered_count}")

#find the heaviest product
heaviest_product = data.loc[data['product_weight_gram'].idxmax()]

#extract or fin d relevant information
heaviest_product_weight = heaviest_product['product_weight_gram']
heaviest_product_quantity = heaviest_product['quantity']
heaviest_product_id = heaviest_product['product_id']
heaviest_product_category = heaviest_product['product_category_name']

print(f"Heaviest product ID: {heaviest_product_id}")
print(f"Heaviest product category: {heaviest_product_category}")
print(f"Weight of the heaviest product (grams): {heaviest_product_weight}")
print(f"Quantity of the heaviest product: {heaviest_product_quantity}")

#now we find the smalles weight with the same method for the heaviest
light_product = data.loc[data['product_weight_gram'].idxmin()]

light_product_weight = light_product['product_weight_gram']
light_product_quantity = light_product['quantity']
light_product_id = light_product['product_id']
light_product_category = light_product['product_category_name']

print(f"light product ID: {light_product_id}")
print(f"light product category: {light_product_category}")
print(f"Weight of the light product (grams): {light_product_weight}")
print(f"Quantity of the light product: {light_product_quantity}")

#just to make sure the column is in datetime format
data['purchase_date'] = pd.to_datetime(data['purchase_date'], dayfirst=True)

#exxtract year and month from 'purchase_date'
data['year_month'] = data['purchase_date'].dt.to_period('M')

#group by the year and month and sum the quantities from 'quanitiy'
monthly_purchases = data.groupby('year_month')['quantity'].sum()

#find the month and year with the highest total quantity
most_purchased_month_year = monthly_purchases.idxmax()
most_purchased_quantity = monthly_purchases.max()

print(f"The month and year with the most purchased products is: {most_purchased_month_year}")
print(f"Total quantity purchased in this month: {most_purchased_quantity}")

Order Details : order_status
delivered      48664
shipped          567
processing       270
canceled         267
invoiced         221
unavailable        7
approved           3
Name: count, dtype: int64
Different type of payment : payment_type
virtual account    12581
credit card        12498
debit card         12472
e-wallet           12448
Name: count, dtype: int64
Different type of category : product_category_name
toys           6375
electronics    6299
automotive     6286
fashion        6274
beauty         6225
gadget         6220
sports         6192
utilities      6128
Name: count, dtype: int64
Total Amount of sales: 130386588000
Average sales / order: 2607783.9156783135
Totalsales / category : product_category_name
automotive     16493552000
beauty         16272726000
electronics    16248782000
fashion        16433729000
gadget         16063418000
sports         16222582000
toys           16604282000
utilities      16047517000
Name: price, dtype: int64
Average weight of product in gram: 2201.830892356943
Category with maximum sales is toys with sales of 16604282000
Category with minimum sales is utilities with sales of 16047517000
Average shipping cost of an order: 104521.39042780855
Top 10 products by quantity sold with category information:
product_id  product_category_name
1894        sports                   53
            utilities                53
            electronics              52
            gadget                   50
            toys                     47
            automotive               40
4506        electronics              39
1894        beauty                   37
4506        beauty                   36
976         toys                     35
dtype: int64
Top 10 sellers by total sales amount:
seller_id
148    3194125000
299    3077753000
707    2636340000
457    2354689000
256    2138824000
31     1910539000
247    1713879000
546    1628130000
354    1583226000
36     1242102000
Name: price, dtype: int64
Total quantity sold per category:
product_category_name
automotive     6286
beauty         6225
electronics    6299
fashion        6274
gadget         6220
sports         6192
toys           6375
utilities      6128
Name: order_id, dtype: int64
Average freight value per seller:
seller_id
1674    199000.0
1748    199000.0
1771    199000.0
1700    198000.0
405     197000.0
1769    195000.0
1691    195000.0
289     194000.0
1658    194000.0
919     192000.0
Name: freight_value, dtype: float64
Top 10 customers by total sales amount:
customer_id
16702    63600000
21856    56762000
35938    39767000
42161    37999000
1051     36726000
38876    36471000
35482    33299000
29612    29381000
26968    27787000
37954    26189000
Name: price, dtype: int64
Customer lifetime value (total sales per customer):
customer_id
16702    63600000
21856    56762000
35938    39767000
42161    37999000
1051     36726000
           ...
23250      201000
11581      201000
28982      200000
35891      200000
10238      200000
Name: price, Length: 42694, dtype: int64
Median sales per order: 2610000.0
Sales distribution by payment type:
payment_type
credit card        32503620000
debit card         32576542000
e-wallet           32346896000
virtual account    32959530000
Name: price, dtype: int64
Most popular payment type: virtual account
Product category with the most canceled orders: beauty
Number of canceled orders in this category: 41
Product category with the most successful orders: toys
Number of delivered orders in this category: 6219
Heaviest product ID: 14175
Heaviest product category: electronics
Weight of the heaviest product (grams): 40425.0
Quantity of the heaviest product: 1
light product ID: 768
light product category: electronics
Weight of the light product (grams): 50.0
Quantity of the light product: 1
The month with the most purchased products is: 2017-11
Total quantity purchased in this month: 10818